/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CancelPay: typeof import('./src/components/payment/sslcom/CancelPay.vue')['default']
    Card: typeof import('./src/components/landing-page/hero/product/Card.vue')['default']
    Category: typeof import('./src/components/landing-page/hero/job-categories/category.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    Fluid: typeof import('primevue/fluid')['default']
    Header: typeof import('./src/components/shared/Header.vue')['default']
    Hero: typeof import('./src/components/product-details/Hero.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Page: typeof import('./src/components/product/Page.vue')['default']
    Password: typeof import('primevue/password')['default']
    PaymentComponent: typeof import('./src/components/payment/PaymentComponent.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./src/components/landing-page/hero/Section.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    ShowBuyProduct: typeof import('./src/components/ShowBuyProduct/ShowBuyProduct.vue')['default']
    SslButton: typeof import('./src/components/payment/sslcom/SslButton.vue')['default']
    SuccessPay: typeof import('./src/components/payment/sslcom/SuccessPay.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
